#!/bin/bash
set -ue

function err_ssh {
  echo error: ssh authentication to www.dontferget.club failed. Please run the following
  echo '$ eval $(ssh-agent -s) && ssh-add <key-file>'
  exit 1
}

container_name=www.dontferget.club
image_name=dontferget-wisp
echo deploying webserver
eval $(docker-machine env www.dontferget.club)
ssh -o BatchMode=yes root@www.dontferget.club 'swapon /swap || :' || err_ssh
docker build -t $image_name -f ./config/webserver.dockerfile .
ssh -o BatchMode=yes root@www.dontferget.club 'swapoff /swap || :' || err_ssh
docker rm -f $container_name || :
docker run -d \
  --restart always \
  -p 80:80 \
  --name $container_name \
  -e MONGO_HOST=10.99.0.10 \
  -e MONGO_DATABASE=todo \
  -e WUNDERLIST_CLIENT_ID=468e63e2114a73908b17 \
  -e WUNDERLIST_CLIENT_SECRET=$(./scripts/secret wunderlist/secret) \
  -e SESSION_SECRET=foobar \
  $image_name
echo done
